# Form implementation generated from reading ui file 'components/add_edit_coffee/addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_add_edit_form(object):
    def setupUi(self, add_edit_form):
        add_edit_form.setObjectName("add_edit_form")
        add_edit_form.resize(705, 330)
        add_edit_form.setMinimumSize(QtCore.QSize(0, 0))
        self.gridLayout = QtWidgets.QGridLayout(add_edit_form)
        self.gridLayout.setContentsMargins(15, 15, 15, 20)
        self.gridLayout.setObjectName("gridLayout")
        self.roast_level = QtWidgets.QLineEdit(parent=add_edit_form)
        self.roast_level.setMinimumSize(QtCore.QSize(125, 30))
        self.roast_level.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.roast_level.setObjectName("roast_level")
        self.gridLayout.addWidget(self.roast_level, 3, 2, 1, 1)
        self.grind_type = QtWidgets.QLineEdit(parent=add_edit_form)
        self.grind_type.setMinimumSize(QtCore.QSize(125, 30))
        self.grind_type.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.grind_type.setObjectName("grind_type")
        self.gridLayout.addWidget(self.grind_type, 3, 4, 1, 1)
        self.variety_name = QtWidgets.QLineEdit(parent=add_edit_form)
        self.variety_name.setMinimumSize(QtCore.QSize(125, 30))
        self.variety_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.variety_name.setObjectName("variety_name")
        self.gridLayout.addWidget(self.variety_name, 3, 0, 1, 2)
        self.taste_description = QtWidgets.QTextEdit(parent=add_edit_form)
        self.taste_description.setObjectName("taste_description")
        self.gridLayout.addWidget(self.taste_description, 5, 0, 1, 7)
        self.package_volume = QtWidgets.QLineEdit(parent=add_edit_form)
        self.package_volume.setMinimumSize(QtCore.QSize(125, 30))
        self.package_volume.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.package_volume.setObjectName("package_volume")
        self.gridLayout.addWidget(self.package_volume, 3, 6, 1, 1)
        self.price = QtWidgets.QLineEdit(parent=add_edit_form)
        self.price.setMinimumSize(QtCore.QSize(125, 30))
        self.price.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.price.setObjectName("price")
        self.gridLayout.addWidget(self.price, 3, 5, 1, 1)
        self.find_add_coffee_Layout = QtWidgets.QHBoxLayout()
        self.find_add_coffee_Layout.setContentsMargins(-1, -1, -1, 20)
        self.find_add_coffee_Layout.setObjectName("find_add_coffee_Layout")
        self.add_edit_CheckBox = QtWidgets.QCheckBox(parent=add_edit_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_edit_CheckBox.sizePolicy().hasHeightForWidth())
        self.add_edit_CheckBox.setSizePolicy(sizePolicy)
        self.add_edit_CheckBox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.add_edit_CheckBox.setStyleSheet("margin-right: 5px;")
        self.add_edit_CheckBox.setObjectName("add_edit_CheckBox")
        self.find_add_coffee_Layout.addWidget(self.add_edit_CheckBox)
        self.id_title_LineEdit = QtWidgets.QLineEdit(parent=add_edit_form)
        self.id_title_LineEdit.setMinimumSize(QtCore.QSize(0, 25))
        self.id_title_LineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.id_title_LineEdit.setObjectName("id_title_LineEdit")
        self.find_add_coffee_Layout.addWidget(self.id_title_LineEdit)
        self.find_PushButton = QtWidgets.QPushButton(parent=add_edit_form)
        self.find_PushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.find_PushButton.setStyleSheet("")
        self.find_PushButton.setObjectName("find_PushButton")
        self.find_add_coffee_Layout.addWidget(self.find_PushButton)
        self.gridLayout.addLayout(self.find_add_coffee_Layout, 0, 0, 2, 7)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=add_edit_form)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Save)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 6, 0, 1, 7)

        self.retranslateUi(add_edit_form)
        QtCore.QMetaObject.connectSlotsByName(add_edit_form)

    def retranslateUi(self, add_edit_form):
        _translate = QtCore.QCoreApplication.translate
        add_edit_form.setWindowTitle(_translate("add_edit_form", "Edd / Edit Coffee"))
        self.roast_level.setText(_translate("add_edit_form", "степень обжарки"))
        self.grind_type.setText(_translate("add_edit_form", "молотый/в зернах"))
        self.variety_name.setText(_translate("add_edit_form", "название сорта"))
        self.taste_description.setHtml(_translate("add_edit_form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Описание вкуса...</p></body></html>"))
        self.package_volume.setText(_translate("add_edit_form", "объем упаковки"))
        self.price.setText(_translate("add_edit_form", "цена"))
        self.add_edit_CheckBox.setText(_translate("add_edit_form", "Изменить"))
        self.id_title_LineEdit.setText(_translate("add_edit_form", "id / Название"))
        self.find_PushButton.setText(_translate("add_edit_form", "Найти"))
